# Generated by Django 6.0 on 2025-12-27 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('capacity_efficiency', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('oee_target', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.workcenter')),
            ],
        ),
    ]
