# Generated by Django 6.0 on 2025-12-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
