# Generated by Django 6.0 on 2025-12-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
